"""
memory.py — Experiment memory management for the BirdCLEF 2026 agent

Saves each experiment in a structured JSON log.
Provides a textual summary to include in prompts for the LLM.
Keeps track of the best AUC achieved.
"""

import json
import os
from datetime import datetime

EXPERIMENTS_DIR = "experiments"
LOG_FILE = os.path.join(EXPERIMENTS_DIR, "experiment_log.json")


class ExperimentMemory:
    def __init__(self):
        """
        Load previous experiments from the log file if it exists.
        Otherwise start from an empty list.
        """
        os.makedirs(EXPERIMENTS_DIR, exist_ok=True)
        self.experiments = []
        self.best_auc = 0.0
        self.best_experiment_id = None

        # Load existing log
        if os.path.exists(LOG_FILE):
            try:
                with open(LOG_FILE, 'r') as f:
                    self.experiments = json.load(f)
                # Recalculate best AUC from loaded experiments
                for exp in self.experiments:
                    auc = exp.get("metrics", {}).get("val_auc", 0) if exp.get("metrics") else 0
                    if auc > self.best_auc:
                        self.best_auc = auc
                        self.best_experiment_id = exp.get("id")
                print(f"Memory loaded: {len(self.experiments)} experiments, best AUC={self.best_auc}")
            except (json.JSONDecodeError, Exception) as e:
                print(f"Error loading memory: {e}")
                self.experiments = []

    def add_experiment(self, prompt, code, result, analysis):
        """
        Add a new experiment to memory and save to disk.

        Args:
            prompt: the prompt sent to the LLM
            code: the code/parameters generated by the LLM
            result: dict with success, stdout, stderr, metrics
            analysis: the LLM's analysis of the results
        """
        exp_id = len(self.experiments) + 1

        # Extract metrics from the result dictionary
        metrics = result.get("metrics", None)
        val_auc = metrics.get("val_auc", 0) if metrics else 0

        # Update best AUC if this experiment is better
        if val_auc > self.best_auc:
            self.best_auc = val_auc
            self.best_experiment_id = exp_id
            print(f"*** NEW RECORD! AUC={val_auc} (experiment #{exp_id}) ***")

        entry = {
            "id": exp_id,
            "timestamp": datetime.now().isoformat(),
            "params_or_code": code[:2000] if isinstance(code, str) else str(code)[:2000],
            "success": result.get("success", False),
            "metrics": metrics,
            "analysis": analysis[:1000] if isinstance(analysis, str) else str(analysis)[:1000],
            "stderr_snippet": result.get("stderr", "")[:500]
        }

        self.experiments.append(entry)
        self._save()

    def _save(self):
        """Save the log to disk in JSON format."""
        try:
            with open(LOG_FILE, 'w') as f:
                json.dump(self.experiments, f, indent=2)
        except Exception as e:
            print(f"Error saving memory: {e}")

    def summarize_recent(self, n=10):
        """
        Produce a textual summary of the last N experiments.
        This text is inserted into the prompt for the LLM.

        Example output:
            Experiment #1: lr=0.001, filters=32/64/128, dropout=0.3
                -> val_auc=0.6326, val_loss=0.0344 (SUCCESS)
            Experiment #2: lr=0.0005, filters=64/128/256, dropout=0.4
                -> val_auc=0.6812, val_loss=0.0298 (SUCCESS) <- BEST
        """
        if not self.experiments:
            return "No previous experiments. This is the first run. Start with a reasonable baseline variation."

        recent = self.experiments[-n:]
        lines = []

        for exp in recent:
            exp_id = exp.get("id", "?")
            success = exp.get("success", False)
            metrics = exp.get("metrics", {})

            # Try to parse parameters if they are JSON
            params_str = ""
            try:
                params = json.loads(exp.get("params_or_code", "{}"))
                if isinstance(params, dict) and "learning_rate" in params:
                    params_str = (
                        f"lr={params.get('learning_rate')}, "
                        f"n_mels={params.get('n_mels', 128)}, "
                        f"n_fft={params.get('n_fft', 2048)}, "
                        f"hop={params.get('hop_length', 512)}, "
                        f"fmin={params.get('fmin', 50)}, "
                        f"fmax={params.get('fmax', 14000)}, "
                        f"top_db={params.get('top_db', 80.0)}, "
                        f"noise={params.get('augmentation_noise', 0.01)}, "
                        f"dropout={params.get('dropout_rate')}, "
                        f"batch={params.get('batch_size')}"
                    )
            except Exception:
                params_str = "custom experiment"
            if success and metrics:
                val_auc = metrics.get('val_auc', 0)
                val_loss = metrics.get('val_loss', 0)
                is_best = " <- BEST" if val_auc == self.best_auc else ""
                lines.append(
                    f"Experiment #{exp_id}: {params_str}\n"
                    f"  -> val_auc={val_auc}, val_loss={val_loss} (SUCCESS){is_best}"
                )
            else:
                error = exp.get("stderr_snippet", "unknown error")[:100]
                lines.append(
                    f"Experiment #{exp_id}: {params_str}\n"
                    f"  -> FAILED: {error}"
                )

        summary = "\n".join(lines)
        summary += f"\n\nCurrent best: val_auc={self.best_auc} (Experiment #{self.best_experiment_id})"

        return summary

    def reliability_stats(self):
        """
        Per-stage success-rate analysis over all logged experiments.

        Stages of the agent pipeline:
          S1  LLM produced text         -- by construction always 1.0
          S2  valid JSON parsed         -- params_or_code parses to a non-empty dict
          S3  subprocess started        -- 'success' field is present (run was launched)
          S4  training completed        -- success == True (no crash, no timeout)
          S5  metrics recovered         -- val_auc present in metrics

        Returns a dict with cumulative counts/rates and stage-conditional rates
        (P(stage k | stage k-1)). The conditional rates make the weak link in
        the pipeline immediately visible.
        """
        n_total = len(self.experiments)
        if n_total == 0:
            return {"n_total": 0}

        n_valid_json = 0
        n_subprocess = 0
        n_completed = 0
        n_metrics = 0

        for e in self.experiments:
            raw = e.get("params_or_code", "")
            try:
                parsed = json.loads(raw) if isinstance(raw, str) else raw
                ok_json = isinstance(parsed, dict) and len(parsed) > 0
            except Exception:
                ok_json = False
            if not ok_json:
                continue
            n_valid_json += 1

            if "success" not in e:
                continue
            n_subprocess += 1

            if e.get("success", False) is not True:
                continue
            n_completed += 1

            m = e.get("metrics")
            if isinstance(m, dict) and m.get("val_auc") is not None:
                n_metrics += 1

        def _ratio(num, den):
            return num / den if den > 0 else 0.0

        return {
            "n_total": n_total,
            "cumulative": {
                "S1_llm_response":       {"count": n_total, "rate": 1.0},
                "S2_valid_json":         {"count": n_valid_json, "rate": _ratio(n_valid_json, n_total)},
                "S3_subprocess_started": {"count": n_subprocess, "rate": _ratio(n_subprocess, n_total)},
                "S4_training_completed": {"count": n_completed, "rate": _ratio(n_completed, n_total)},
                "S5_metrics_recovered":  {"count": n_metrics, "rate": _ratio(n_metrics, n_total)},
            },
            "conditional": {
                "P_S2_given_S1": _ratio(n_valid_json, n_total),
                "P_S3_given_S2": _ratio(n_subprocess, n_valid_json),
                "P_S4_given_S3": _ratio(n_completed, n_subprocess),
                "P_S5_given_S4": _ratio(n_metrics, n_completed),
            },
        }

    def print_reliability_report(self):
        """Pretty-print the per-stage reliability table to stdout."""
        stats = self.reliability_stats()
        if stats.get("n_total", 0) == 0:
            print("No experiments logged yet.")
            return
        print("=" * 64)
        print(f"AGENT RELIABILITY REPORT (over {stats['n_total']} logged experiments)")
        print("=" * 64)
        print(f"{'Stage':<32s}{'Count':>10s}{'Rate':>10s}{'Cond.':>10s}")
        print("-" * 64)
        cum = stats["cumulative"]
        cond = stats["conditional"]
        rows = [
            ("S1 LLM produced text",       cum["S1_llm_response"],       1.0),
            ("S2 valid JSON parsed",       cum["S2_valid_json"],         cond["P_S2_given_S1"]),
            ("S3 subprocess started",      cum["S3_subprocess_started"], cond["P_S3_given_S2"]),
            ("S4 training completed",      cum["S4_training_completed"], cond["P_S4_given_S3"]),
            ("S5 metrics recovered",       cum["S5_metrics_recovered"],  cond["P_S5_given_S4"]),
        ]
        for name, c, p_cond in rows:
            print(f"{name:<32s}{c['count']:>10d}{c['rate']:>10.3f}{p_cond:>10.3f}")
        print("=" * 64)
        print("Cond. = P(this stage succeeds | previous stage succeeded).")
        print("Lowest conditional rate identifies the weakest link in the pipeline.")